name: Deploy to Azure Web App

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  auth-with-azure:
    name: Authenticate with Azure
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  build-and-deploy-react-image:
    name: Build and Deploy React Image
    runs-on: ubuntu-latest
    needs: auth-with-azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f /client/dockerfile.front -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/queryclient:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/queryclient:${{ github.sha }}

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/queryclient:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-queryclient
          location: "centralindia"

  build-and-deploy-fastapi-image:
    name: Build and Deploy FastAPI Image
    runs-on: ubuntu-latest
    needs: auth-with-azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f /api/dockerfile.back -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/queryfastapi:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/queryfastapi:${{ github.sha }}

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: fastapi${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/queryfastapi:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-queryfastapi
          location: "centralindia"
