name: Deploy to Azure Web App

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  auth-with-azure:
    name: Authenticate with Azure
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


  build-and-deploy-fastapi:
    name: Build and Deploy FastAPI Application
    runs-on: ubuntu-latest
    needs: auth-with-azure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./api

      - name: Build the application
        run: |
          echo "Building the application..."
        working-directory: ./api

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ secrets.AZURE_API_WEBAPP_NAME }}
          slot-name: "Production"

  build-and-deploy-client:
    name: Build and Deploy React Client
    runs-on: ubuntu-latest
    needs: auth-with-azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Write secrets to .env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
        working-directory: ./client

      - name: Build project
        run: npm run build
        working-directory: ./client

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./client/build
